package gui;

import dao.DAOException;
import dao.ProductDataInterface;
import domain.Product;
import gui.helpers.SimpleListModel;
import gui.helpers.ValidationHelper;
import java.math.BigDecimal;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author dinjo998
 */
public class ProductEditor extends javax.swing.JDialog {

	private final ProductDataInterface dao;
	private SimpleListModel myModel = new SimpleListModel();
	private Product product = new Product();
	private ValidationHelper validHelp = new ValidationHelper();
	
	/**
	 * Creates new form ProductEditor
	 * @param parent
	 * @param modal
	 * @param dao
	 */
	public ProductEditor(java.awt.Window parent, boolean modal, ProductDataInterface dao) {
		super(parent);
		super.setModal(modal);
		this.dao = dao;
		initComponents();
		txtCategory.setEditable(true);
		Collection<String> collection = dao.getCategory();
		myModel.updateItems(collection);
		txtCategory.setModel(myModel);
		// add a formatter to the price text field
		validHelp.addTypeFormatter(txtPrice, "#0.00", BigDecimal.class);
		validHelp.addTypeFormatter(txtQuantity, "#0.00", BigDecimal.class);
	}
	
	public ProductEditor(java.awt.Window parent, boolean modal, 
			  Product productToEdit, ProductDataInterface dao) {
		this(parent, modal, dao);
		this.product = productToEdit;
		txtID.setText(product.getProductID());
		txtID.setEditable(false);
		txtName.setText(product.getName());
		txtDescription.setText(product.getDescription());
		txtCategory.setSelectedItem(product.getCategory());
		txtPrice.setValue(product.getPrice());
		txtQuantity.setValue(product.getQuantity());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      txtID = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtName = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtDescription = new javax.swing.JTextArea();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      saveButton = new javax.swing.JButton();
      cancelButton = new javax.swing.JButton();
      txtCategory = new javax.swing.JComboBox<>();
      txtPrice = new javax.swing.JFormattedTextField();
      txtQuantity = new javax.swing.JFormattedTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jLabel1.setText("ID:");
      jLabel1.setName("jLabel1"); // NOI18N

      txtID.setName("txtID"); // NOI18N

      jLabel2.setText("Name:");
      jLabel2.setName("jLabel2"); // NOI18N

      txtName.setName("txtName"); // NOI18N

      jLabel3.setText("Description:");
      jLabel3.setName("jLabel3"); // NOI18N

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      txtDescription.setColumns(20);
      txtDescription.setRows(5);
      txtDescription.setName("txtDescription"); // NOI18N
      jScrollPane1.setViewportView(txtDescription);

      jLabel4.setText("Category:");
      jLabel4.setName("jLabel4"); // NOI18N

      jLabel5.setText("Price:");
      jLabel5.setName("jLabel5"); // NOI18N

      jLabel6.setText("Quantity in Stock:");
      jLabel6.setName("jLabel6"); // NOI18N

      saveButton.setText("Save");
      saveButton.setName("saveButton"); // NOI18N
      saveButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveButtonActionPerformed(evt);
         }
      });

      cancelButton.setText("Cancel");
      cancelButton.setName("cancelButton"); // NOI18N
      cancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelButtonActionPerformed(evt);
         }
      });

      txtCategory.setEditable(true);
      txtCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      txtCategory.setToolTipText("");
      txtCategory.setName("txtCategory"); // NOI18N
      txtCategory.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtCategoryActionPerformed(evt);
         }
      });

      txtPrice.setName("txtPrice"); // NOI18N

      txtQuantity.setName("txtQuantity"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                  .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtID)
                     .addComponent(txtName)
                     .addComponent(txtCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jScrollPane1)
                     .addComponent(txtPrice)
                     .addComponent(txtQuantity))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel3)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(cancelButton)
               .addComponent(saveButton))
            .addGap(27, 27, 27))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		try {
			String productID = txtID.getText();
			String name = txtName.getText();
			String description = txtDescription.getText();
			String category = (String) txtCategory.getSelectedItem();
			BigDecimal price = (BigDecimal) txtPrice.getValue();
			BigDecimal quantity = (BigDecimal) txtQuantity.getValue();

			//set details into product object
			product.setProductID(productID);
			product.setName(name);
			product.setDescription(description);
			product.setCategory(category);
			product.setPrice(price);
			product.setQuantity(quantity);

			//check is product details are valid
			if (validHelp.isObjectValid(product)) {
				if (txtID.isEditable() && !(dao.searchByID(productID) == null)) {
					JOptionPane.showMessageDialog(this, "A product already exists with "
							  + "this Product ID.", "Error",
							  JOptionPane.WARNING_MESSAGE);
				} else {
					dao.saveProduct(product);
					dispose();
				}
			}
		} catch (DAOException ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Message", JOptionPane.INFORMATION_MESSAGE);
			throw new DAOException(ex.getMessage(), ex);
		}
   }//GEN-LAST:event_saveButtonActionPerformed

   private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtCategoryActionPerformed

   private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      // TODO add your handling code here:
		dispose();
   }//GEN-LAST:event_cancelButtonActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton cancelButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JButton saveButton;
   private javax.swing.JComboBox<String> txtCategory;
   private javax.swing.JTextArea txtDescription;
   private javax.swing.JTextField txtID;
   private javax.swing.JTextField txtName;
   private javax.swing.JFormattedTextField txtPrice;
   private javax.swing.JFormattedTextField txtQuantity;
   // End of variables declaration//GEN-END:variables
}
