@startuml
' use strict UML mode
skinparam style strictuml

actor "User" as user

participant "Application" as main <<main>>
main++

create "ProductDAO" as dao <<DAO>>
main -> dao : construct

create "MainMenu" as menu <<frame>>
main -> menu : construct(dao)

main -> menu++ : setVisible(true)

user -> menu++ : click 'view all products'

create "ProductReport" as report <<dialog>>
menu -> report : construct(dao)

report++

report -> dao++ : getProducts()
return products

create "SimpleListModel" as model <<model>>
report -> model : construct

report -> model++ : updateItems(products)
model--
report -> report : productsList.setModel(model)

menu -> report : setVisible(true)

' user enters product ID and clicks the search button
user -> report++: enters product ID

report--

user -> report++ : clicks search button


report -> report : getText() : productID

report -> dao++ : searchByID(productID)
return productsByID
dao--

report -> model++ : updateItems(productsByID)
model--

report -> report : productsList.setModel(model)
report -> user : products are visible to user
@enduml